<?php

/**
 * @file
 * Provides a league entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function fifa_league_theme() {
  return [
    'fifa_league' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for league templates.
 *
 * Default template: fifa-league.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the league information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_fifa_league(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
