<?php

/**
 * @file
 * Provides a group entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function fifa_group_theme() {
  return [
    'fifa_group' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for group templates.
 *
 * Default template: fifa-group.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the group information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_fifa_group(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
