<?php

/**
 * @file
 * Provides a club entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function fifa_club_theme() {
  return [
    'fifa_club' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for club templates.
 *
 * Default template: fifa-club.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the club information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_fifa_club(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_views_data() for Club entities.
 */
function fifa_club_views_data() {

  $data['fifa_club__field_person']['field_person_target_id'] = [
 
    'relationship' => [
      'title' => t('Person relationship'),
      'help' => t('The detail personal information of member.'),
      'group' => t('Fifa'),
      'label' => t("Person"),      
      'base' => 'fifa_person',
      'base field' => 'id',
      'relationship field' => 'field_person_target_id',
      'id' => 'standard',
    ],    
  ];

  return $data;

}